#!/bin/sh
#_chromium=${$_CHROMIUM:-"$(which chromium)"}
# set CHROME_USER_DATA_DIR to persistent profile (with separate theme)
#    --user-data-dir=$CHROME_USER_DATA_DIR

# Custom flags are read in order from the following files:

# + /etc/chromium-flags.conf
# + /home/dc/.config/chromium-flags.conf

cr_window_name=makeroanoke
cr_app_id=makeroanoke
cr_class_name=makeroanoke

# TODO: chromium=$(flatpak run com.google.chrome...)

# CHROME_USER_DATA=/tmp/.config/chromium

url=${1:-"http://0.0.0.0:4000"}

chromium --app-id=$_cr_app_id \
      --class=$_cr_class_name \
      --user-data-dir=$CHROME_USER_DATA \
      $url 2>&1 >/dev/null & disown

# && xdotool search --sync \
#    --classname iHubChromium \
#    set_window --class iHubChromium
